[package]
name = "damsel-macho"
version.workspace = true
edition.workspace = true

[dependencies]
damsel-core = { path = "../damsel-core" }
goblin.workspace = true
memmap2.workspace = true
object.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "decode_bench"
harness = false
