[package]
name = "damsel-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
damsel-core = { path = "../damsel-core" }
damsel-macho = { path = "../damsel-macho" }

[dev-dependencies]
assert_cmd.workspace = true
insta.workspace = true
predicates.workspace = true
