[package]
name = "damsel-cli"
version.workspace = true
edition.workspace = true
description = "Private CLI for Damsel Mach-O arm64/arm64e analysis workflows."
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
axum.workspace = true
clap.workspace = true
damsel-core = { path = "../damsel-core" }
damsel-macho = { path = "../damsel-macho" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
webbrowser.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
insta.workspace = true
predicates.workspace = true
reqwest.workspace = true
serde_json.workspace = true
