[package]
name = "damsel-cli"
version.workspace = true
edition.workspace = true
description = "Private CLI for Damsel Mach-O arm64/arm64e analysis workflows."
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
clap.workspace = true
damsel-core = { path = "../damsel-core" }
damsel-macho = { path = "../damsel-macho" }

[dev-dependencies]
assert_cmd.workspace = true
insta.workspace = true
predicates.workspace = true
serde_json.workspace = true
